Repository Tave100Shot/Frontend, pull requests merged in 2024-01, with the labels that each got.

#35 23 solution page 기능 추가 구현
  src/App.js
  src/assets/imgs/githubBlog.png
  src/assets/imgs/naverIcon.png
  src/assets/imgs/personIcon.png
  src/assets/imgs/tistoryIcon.png
  src/assets/imgs/verlogIcon.png
  src/components/solution/search_bar.js
  src/components/solution/solutionItem.js
  src/pages/solution/solutionPage.js
  src/redux/actions/solutionAction.js
  src/redux/reducers/reducer.js
  src/styles/searchBarStyle.js
  src/styles/solutionStyle.js
  src/styles/theme.js
Labels: Feature, 장진영

#36 33 main page 기능 추가 구현
  src/App.js
  src/assets/imgs/baekjoon.png
  src/assets/imgs/baekjoon_auth.png
  src/assets/imgs/step3_편집.png
  src/assets/imgs/갤럭시.png
  src/assets/imgs/아이폰.png
  src/components/common/Header.js
  src/components/main/addAuthModal.js
  src/components/main/mainButton.js
  src/components/main/tave_animation.js
  src/index.js
  src/pages/main/MainPage.js
  src/pages/main/mobilePage.js
  src/redux/actions/mainAction.js
  src/redux/reducers/reducer.js
  src/styles/GlobalStyle.js
  src/styles/loginModalStyle.js
  src/styles/mobileStyle.js
Labels: BugFix, Feature, 장진영

#41 37 recommend page 기능 구현
  src/App.js
  src/components/main/addAuthModal.js
  src/components/main/altButton.js
  src/components/main/mainButton.js
  src/components/recommend/recommend_me.js
  src/components/recommend/recommend_rival.js
  src/components/recommend/tierBadge.js
  src/components/recommend/user_profile.js
  src/pages/main/MainPage.js
  src/pages/recommend/RecommendPage.js
  src/redux/actions/recommendAction.js
  src/redux/reducers/reducer.js
  src/styles/RecommendMainStyle.js
  src/styles/loginModalStyle.js
  src/styles/mainButtonStyle.js
  src/styles/mainPageStyle.js
  src/styles/recommendProblemStyle.js
  src/styles/theme.js
Labels: Feature, 장진영

#47 Cicd front cicd docker + nginxconfig
  dockerfile
  nginx.conf
  package.json
  public/index.html
  public/manifest.json
  src/App.js
  src/components/common/Header.js
  src/components/main/addAuthModal.js
  src/components/solution/search_bar.js
  src/index.js
  src/pages/community/WritePage.js
  src/pages/solution/SearchPage.js
  src/pages/solution/solutionPage.js
  src/pages/test.js
  src/setProxy.js
Labels: :construction_worker: CI/CD, 임준형

#51 CI/CD : 1차 배포 수정
  src/components/main/addAuthModal.js
  src/components/recommend/recommend_me.js
  src/components/recommend/recommend_rival.js
  src/components/recommend/tierBadge.js
  src/pages/recommend/RecommendPage.js
  src/styles/RecommendMainStyle.js
  src/styles/recommendProblemStyle.js
Labels: 장진영, :construction_worker: CI/CD

#62 #61 fix: 없는 문제 에러 처리
  src/components/solution/search_bar.js
  src/pages/compiling/CompilingPage.js
  src/pages/recommend/RecommendPage.js
Labels: BugFix, 장진영
