Repository Tave100Shot/Frontend, pull requests merged in 2024-03, with the labels that each got.

#78 Refactor : main page 코드 리펙토링
  README.md
  public/index.html
  public/manifest.json
  src/App.js
  src/assets/imgs/1step_편집.png
  src/assets/imgs/baekjoon_auth.png
  src/assets/imgs/baekjoon_icon.png
  src/assets/imgs/left_black.png
  src/assets/imgs/right_black.png
  src/assets/imgs/step1.png
  src/assets/imgs/step2.png
  src/assets/imgs/step2_편집.png
  src/assets/imgs/step3.png
  src/assets/imgs/step3_편집.png
  src/components/common/header.js
  src/components/main/addAuthModal.js
  src/components/main/altButton.js
  src/components/main/mainButton.js
  src/components/main/modalItem.js
  src/components/main/taveAnimation.js
  src/index.js
  src/pages/main/mainPage.js
  src/pages/main/mobilePage.js
  src/setProxy.js
  src/styles/main/loginModalStyle.js
  src/styles/main/mainButtonStyle.js
  src/styles/main/mainPageStyle.js
  src/styles/main/mobileStyle.js
  src/styles/main/taveAnimationStyle.js
Labels: Refactor, 장진영

#82 Refactor : solution page 코드 리펙토링
  src/components/solution/searchBar.js
  src/components/solution/solutionItem.js
  src/components/solution/solutionText.js
  src/pages/solution/searchPage.js
  src/pages/solution/solutionPage.js
  src/redux/reducer.js
  src/store.js
  src/styles/solution/searchBarStyle.js
  src/styles/solution/solutionStyle.js
  src/styles/solution/solutionTextStyle.js
Labels: Refactor, 장진영

#84 Refactor : #83 recommend page 리팩토링
  src/components/common/header.js
  src/components/main/altButton.js
  src/components/main/mainButton.js
  src/components/main/taveAnimation.js
  src/components/main/todayQuestions.js
  src/pages/main/mainPage.js
  src/styles/main/mainButtonStyle.js
  src/styles/main/taveAnimationStyle.js
  src/styles/main/todayQuestionStyle.js
Labels: Feature, Refactor, 장진영

#88 Refactor : 파라미터로 2차 인증 여부 받아오기 (#85)
  src/components/common/header.js
  src/pages/main/mainPage.js
Labels: Refactor, 장진영

#87 Feat : 백발백준 소개 미니 배너 기능 구현 (#86)
  src/assets/fonts/WantedSans-Black.woff2
  src/assets/fonts/WantedSans-Bold.woff2
  src/assets/fonts/WantedSans-ExtraBlack.woff2
  src/assets/fonts/WantedSans-ExtraBold.woff2
  src/assets/fonts/WantedSans-Medium.woff2
  src/assets/fonts/WantedSans-Regular.woff2
  src/assets/fonts/WantedSans-SemiBold.woff2
  src/assets/imgs/introButton.png
  src/assets/imgs/modalImage.png
  src/components/main/addAuthModal.js
  src/components/main/introButton.js
  src/pages/main/mainPage.js
  src/styles/globalStyle.js
  src/styles/main/introBtnStyle.js
  src/styles/main/loginModalStyle.js
  src/styles/main/mainPageStyle.js
  src/styles/theme.js
Labels: Feature, 장진영

#89 81 community page 오류 처리하기
  src/pages/community/postDetailPage.js
  src/styles/communityPostStyle.js
  src/styles/communityStyle.js
Labels: Refactor, 김소정
